test 3.9:
  image: python:3.9
  stage: test
  before_script:
    - pip install responses
    - pip install -r requirements.txt
    - pip install coveralls
  script:
    - cd ./tests
    - coverage run --source=.. --omit=../lib/* ./all_tests.py
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"

test 3.10:
  image: python:3.10
  stage: test
  before_script:
    - pip install responses
    - pip install -r requirements.txt
    - pip install coveralls
  script:
    - cd ./tests
    - coverage run --source=.. --omit=../lib/* ./all_tests.py
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"

test 3.11:
  image: python:3.11
  stage: test
  before_script:
    - pip install responses
    - pip install -r requirements.txt
    - pip install coveralls
  script:
    - cd ./tests
    - coverage run --source=.. --omit=../lib/* ./all_tests.py
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"

test 3.12:
  image: python:3.12
  stage: test
  before_script:
    - pip install responses
    - pip install -r requirements.txt
    - pip install coveralls
  script:
    - cd ./tests
    - coverage run --source=.. --omit=../lib/* ./all_tests.py
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"

test 3.13:
  image: python:3.13
  stage: test
  before_script:
    - pip install responses
    - pip install -r requirements.txt
    - pip install coveralls
  script:
    - cd ./tests
    - coverage run --source=.. --omit=../lib/* ./all_tests.py
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"

