name: sickgear
summary: SickGear
description: |
  SickGear has proven the most reliable stable TV fork of the great Sick-Beard to fully automate TV enjoyment with innovation.

  Typically used with a download client e.g. nzbget, sabnzbd, qBittorrent, transmission, deluge, rtorrent and others.

  Home: https://github.com/SickGear/SickGear
  Wiki: https://github.com/SickGear/SickGear/wiki
  Issues: https://github.com/SickGear/SickGear/issues

icon: gui/slick/images/sickgear.png
confinement: strict
adopt-info: sickgear

apps:
  sickgear:
    command: python "$SNAP/sickgear/sickgear.py" --datadir="$SNAP_COMMON/data"
    # daemon: simple
    plugs: [network, network-bind, removable-media]

parts:
  sickgear:
    plugin: python
    source: .
    python-version: python2
    python-packages: [cheetah3, cryptography, lxml, regex, scandir]
    build-attributes: [no-system-libraries]

    stage-packages:
    - libffi-dev
    - libssl-dev
    - p7zip-full
    - python-dev
    - unrar

    build-packages:
    - libffi-dev
    - libssl-dev
    - libxslt1-dev
    - libxml2-dev
    - p7zip-full
    - python-dev
    - python-lxml
    - python-regex
    - unrar

    override-pull: |
      snapcraftctl pull

      [ -z $(grep -o 'xx:xx:xx' CHANGES.md) ] && grade=stable || grade=devel
      snapcraftctl set-grade "$grade"

      version="$(sed -n '1 s/###[^0-9]\{1,\}\([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\).*/\1/p' CHANGES.md)"
      # removes unicode before assignment
      snapcraftctl set-version "$(echo ${version} | sed 's/[^0-9\.]//g')"

    override-build: |
      snapcraftctl build

      snap_install="$SNAPCRAFT_PART_INSTALL/sickgear"
      mkdir -p "$snap_install"
      cp -R "$SNAPCRAFT_PART_BUILD"/* "$snap_install"
      # unrequired on r/o systems
      rm -rf "$snap_install/tests" \
             "$snap_install/_cleaner.py" \
             "$snap_install/HACKS.txt" \
             "$snap_install/requirements.txt" \
             "$snap_install/tox.ini"

    override-prime: |
      snapcraftctl prime

      snap_current=$(printf "${SNAP_COMMON}" | sed -e "s/common/current/" -e "s/snapcraft/sickgear/")
      cat > "$SNAPCRAFT_PRIME/sickgear/_SNAP_README.txt" <<EOT
      For ease of use, autoProcessTV scripts for use in third party applications are
      placed in the writable path $snap_current/ so that editable config
      files are copied into latest revision folders created by the snap update system.

      Examples, create config file from templates;
      for Sabnzbd, create autoProcessTV.cfg from autoProcessTV.cfg.sample
      for Deluge or Transmission, create onTxComplete.cfg from onTxComplete.sample.cfg

      In clients, when specifying a download completed script location;
      for Sabnzbd, $snap_current/autoProcessTV/sabToSickBeard.py
      for NzbGet, $snap_current/autoProcessTV/SickGear-NG/SickGear-NG.py
      for Torrent (*nix), $snap_current/autoProcessTV/onTxComplete.sh
      for Torrent (Win), $snap_current/autoProcessTV/onTxComplete.bat
      EOT
